spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

logging:
  level:
    org.springframework.batch: DEBUG

---
spring:
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
spring:
  profiles:
    active: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:33306/spring_batch
      username: blackbear
      password: a123456A!
      driver-class-name: com.mysql.cj.jdbc.Driver